# Config dedicated for module A
# All the resources must be prefixed with `module-a-` to avoid conflicts

version: 2.1

jobs:
  build-App1:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout:
          path: /home/circleci/project
      - run:
          command: |
            python module-a/app1.py

workflows:
  module-a-workflow:
     jobs:
      - build-App1
