# Config for the setup workflow and common resources (jobs, commands) for main workflows
# `common-` prefix is added for common resources (to avoid conflicts with module resources)

version: 2.1

setup: << pipeline.parameters.run-setup >>

# All pipeline parameters need to be defined equally both for the setup workflow and main workflows
# These parameters will be passed to both of them
parameters:
  run-setup:
    description: Whether it is a setup workflow or a continuation
    type: boolean
    default: true
  custom-parameter:
    description: Some string to pass
    type: string
    default: ""

workflows:
  # The setup workflow
  setup-workflow:
    when: << pipeline.parameters.run-setup >>
    jobs:
      - test-orb-circleci/setup-dynamic-config:
          base-revision: main
          # If A is modified, the job for A will run
          # Similarly if B is modified, the job for B will run
          # If C is modified, then the jobs for both C and B (as a dependency) will run
          modules: |
            module-a
            b
            module-c b

orbs:
  # An "embedded" orb to facilitate config splitting
  test-orb-circleci: namespace_jonnathan_test/test-orb-circleci@0.0.6
  
