# Config dedicated for module C

version: 2.1

jobs:
  build-App3:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout:
          path: /home/circleci/project
      - run:
          command: |
            python module-c/app3.py

workflows:
  module-c-workflow:
     jobs:
      - build-App3
