# Config dedicated for module B
# All the resources must be prefixed with `module-b-` to avoid conflicts

version: 2.1

jobs:
  build-App2:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout:
          path: /home/circleci/project
      - run:
          command: |
            python b/app2.py

workflows:
  module-b-workflow:
     jobs:
      - build-App2
